jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: copy checked out dir to /c/jena for windows-latest
      run: bash -c "cp -r /d/a/jena/jena /c/jena"
    - continue-on-error: true
      name: Build with Maven for windows-latest
      run: bash -c "mvn -B --file pom.xml -Dmaven.javadoc.skip=true install"
      working-directory: c:\jena
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
name: Apache Jena CI (MS Windows)
on:
  repository_dispatch:
    types: trigger-ga___maven_windows.yml
permissions:
  contents: read
